   name: Build, Push, and Run Docker Image with ngrok

   on:
     push:
       branches:
         - main
     pull_request:
       branches:
         - main

   jobs:
     build:
       runs-on: ubuntu-latest

       steps:
         - name: Checkout repository
           uses: actions/checkout@v2

         - name: Set up Docker Buildx
           uses: docker/setup-buildx-action@v1

         - name: Log in to GitHub Container Registry
           uses: docker/login-action@v1
           with:
             registry: ghcr.io
             username: ${{ github.repository_owner }}
             password: ${{ secrets.GITHUB_TOKEN }}

         - name: Set lowercase repository owner
           id: vars
           run: echo "REPO_OWNER_LOWER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

         - name: Build and push Docker image
           uses: docker/build-push-action@v2
           with:
             context: .
             push: true
             tags: ghcr.io/${{ env.REPO_OWNER_LOWER }}/tgui-example:latest

         - name: Run Docker container
           run: |
             docker run -d -p 3000:3000 --name tgui-example ghcr.io/${{ env.REPO_OWNER_LOWER }}/tgui-example:latest

         - name: Install ngrok
           run: |
             sudo apt-get update
             sudo apt-get install -y unzip
             curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
             echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
             sudo apt-get update && sudo apt-get install ngrok

         - name: Start ngrok
           run: |
             ngrok http 3000 &

         - name: Display ngrok URL
           id: ngrok
           run: |
             sleep 5
             NGROK_URL=$(curl --silent http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url')
             echo "NGROK_URL=${NGROK_URL}" >> $GITHUB_ENV
             echo "ngrok URL: ${NGROK_URL}"

         - name: Keep the container running
           run: |
             while true; do sleep 1000; done
