   name: Build, Push, and Run Docker Image

   on:
     push:
       branches:
         - main
     pull_request:
       branches:
         - main

   jobs:
     build:
       runs-on: ubuntu-latest

       steps:
         - name: Checkout repository
           uses: actions/checkout@v2

         - name: Set up Docker Buildx
           uses: docker/setup-buildx-action@v1

         - name: Log in to GitHub Container Registry
           uses: docker/login-action@v1
           with:
             registry: ghcr.io
             username: ${{ github.repository_owner }}
             password: ${{ secrets.GITHUB_TOKEN }}

         - name: Build and push Docker image
           uses: docker/build-push-action@v2
           with:
             context: .
             push: true
             tags: ghcr.io/${{ github.repository_owner.toLowerCase() }}/tgui-example:latest

         - name: Run Docker container
           run: |
             docker run -d -p 3000:3000 --name tgui-example ghcr.io/${{ github.repository_owner.toLowerCase() }}/tgui-example:latest

         - name: Wait for container to be ready
           run: |
             sleep 10

         - name: Test the running container
           run: |
             curl -f http://localhost:3000 || (docker logs tgui-example && exit 1)

         - name: Stop and remove Docker container
           run: |
             docker stop tgui-example
             docker rm tgui-example
